api/urls.py
from django.urls import path

from api import views

app_name = "api"

urlpatterns = [
    path('v1/list/grantgoal/', views.ListGrantGoalAPIView.as_view(), name='list_gg_api'),
    path('v1/detail/grantgoal/<int:pk>/', views.DetailGrantGoalAPIView.as_view(), name='detail_gg_api'),
]

home/urls.py
from django.urls import path

from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('logout/', views.LogOut.as_view(), name="logout"),
    path('singup/', views.SingUp.as_view(), name="singup"),

    ##PROFILE URLS ##
    path('list/profile/', views.ListProfile.as_view(), name="list_profile"),
    path('detail/profile/<int:pk>/', views.DetailProfile.as_view(), name="detail_profile"),
]

pem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from core.models import Area

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=128, default="I love plesem system")
    avatar = models.ImageField(blank=True, null=True)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=32)

    def __str__(self):
        return self.user.first_name

@receiver(post_save, sender=User)
def auto_profile(sender, instance, **kwargs):
    if kwargs.get('created', False):
        Profile.objects.get_or_create(user=instance, slug=instance.username)

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

class LoginForm(forms.Form):
    username = forms.CharField(max_length=32, widget=forms.TextInput(attrs={"type":"text",'class': 'form-control'}))
    password = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={"type":"password",'class': 'form-control'}))

class SingUpForm(UserCreationForm):
    username = forms.CharField(max_length=32, widget=forms.TextInput(attrs={"type":"text",'class': 'form-control'}))
    password1 = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={"type":"password",'class': 'form-control'}))
    password2 = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={"type":"password",'class': 'form-control'}))
    email = forms.EmailField(max_length=64, widget=forms.EmailInput(attrs={"type":"email",'class': 'form-control'}))
    first_name = forms.CharField(max_length=32, widget=forms.TextInput(attrs={"type":"text",'class': 'form-control'}))
    last_name = forms.CharField(max_length=32, widget=forms.TextInput(attrs={"type":"text",'class': 'form-control'}))
  

home/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy

from .forms import LoginForm, SingUpForm
from .models import Profile
# Create your views here.


class Index(generic.View):
    template_name = "home/index.html"
    context = {}
    form_class = LoginForm

    def get(self, request):
        self.context = {
            "users": User.objects.all(),
            "form": self.form_class
        }
        return render(request, self.template_name, self.context)

    def post(self, request):
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            redirect("home:index")
        return redirect('home:index')


class LogOut(generic.View):
    def get(self, request):
        logout(request)
        return redirect("home:index")

class SingUp(generic.CreateView):
    template_name = "home/singup.html"
    model = User
    form_class = SingUpForm
    success_url = reverse_lazy("home:index")

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get("username")
        password1= form.cleaned_data.get("password1")
        user = authenticate(self.request, username=username, password=password1)
        if user is not None:
            login(self.request, user)
        return redirect('home:index')

class ListProfile(generic.View):
    template_name = "home/list_profile.html"
    context = {}

    def get(self, request):
        self.context = {
            "profiles": Profile.objects.filter(status=True)
        }
        return render(request, self.template_name, self.context)
    
class DetailProfile(generic.DetailView):
    template_name = "home/detail_profile.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "profile": Profile.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)

templates/home/detail_profile.html
{% extends "base/base.html"%}

{% block title%} DETAIL PROFILE VIEW {% endblock title %}

{% block content %}
    <h3>{{profile.user.first_name}}</h3>

    <a href="{%url 'home:list_profile' %}">Return</a>
{% endblock content%}

templates/home/index.html
{% extends 'base/base.html' %}

{% block title %}INDEX VIEW {% endblock title %}

   <h1>Hola Mundo Django XD ...</h1>

   {% block content %}
    {% if request.user.is_authenticated %}
   <h3 class="">Welcome user : {{ request.user.username }} to plesem system control panel!</h3>
        <table class="table table-striped">
            <thead>
                <th>ID</th>
                <th>Name</th>
                <th>EMAIL</th>
                <th></th>
                <th>ACTIONS</th>
                <th></th>
            </thead>
            <tbody>
                {% for user in users %}
                    <tr>
                        <td>{{ user.id }}</td>
                        <td>{{ user.username }}</td>
                        <td>{{ user.email}}</td>
                        <td><a href="" class="btn btn-outline-info">detail</a></td>
                        <td><a href="" class="btn btn-outline-warning">update</a></td>
                        <td><a href="" class="btn btn-outline-danger">delete</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
            <form action="" method="post">
                {% csrf_token %}
                    {{ form }}
                <button type="submit" class="btn btn-primary form-control">LogIn</button>
                <a href="{% url 'home:index' %}" class="btn btn-outline-warning form-control"> Cancel</a>
            </form>
            <h4>If you don't have account, Make your register <a href="{% url 'home:singup' %}">Here</a></h4>
        {% endif %}
        
{% endblock content %}

templates/home/list_profile.html
{% extends "base/base.html"%}

{% block title%} LIST PROFILE VIEW {% endblock %}

{% block content %}
    <table class="table table-striped">
        <thead>
            <th>id</th>
            <th>PROFILE NAME</th>
            <th>TIMESTAMP</th>
            <th>STATUS</th>
            <th></th>
            <th>ACTIONS</th>
        </thead>
        <body>
            {% for profile in profiles%}
                <tr>
                    <td>{{profile.id}}</td>
                    <td>{{profile.user.first_name}}</td>
                    <td>{{profile.timestamp}}</td>
                    <td>{{profile.status}}</td>
                    <td><a href="{% url 'home:detail_profile' profile.id %}" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </body>
    </table>
{% endblock content %}

templates/home/signup.html
{% extends 'base/base.html' %}


{% block title %} SINGUP VIEW {% endblock title %}

{% block content %}
    <h1>Register new user</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-succes form-control">SingUp</button>
        <a href="{% url 'home:index' %}" class="btn btn-outline-warning form-control"> Cancel</a>
    </form>
{% endblock content %}