api/urls.py
from django.urls import path

from api import views

app_name = "api"

urlpatterns = [
    path('v1/list/grantgoal/', views.ListGrantGoalAPIView.as_view(), name='list_gg_api'),
    path('v1/detail/grantgoal/<int:pk>/', views.DetailGrantGoalAPIView.as_view(), name='detail_gg_api'),
]

core/urls.py
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
    path('list/grantgoal/', views.ListGrantGoal.as_view(), name="list_gg"),
    path('new/grantgoal/', views.NewGrantGoal.as_view(), name="create_gg"),
    path('detail/grantgoal/<int:pk>/', views.DetailGrantGoal.as_view(), name="detail_gg"),
    path('update/grantgoal/<int:pk>/', views.UpdateGrantGoal.as_view(), name="update_gg"),
    path('delete/grantgoal/<int:pk>/', views.DeleteGrantGoal.as_view(), name="delete_gg"),
    ### SUBGRANTGOALS URLS ###
    path('list/subgrantgoal/', views.ListSubGrantGoal.as_view(), name="list_sgg"),
    path('detail/subgrantgoal/<int:pk>/', views.DetailSubGrantGoal.as_view(), name="detail_sgg"),
    path('new/subgrantgoal/', views.NewSubGrantGoal.as_view(), name="create_sgg"),
    path('update/subgrantgoal/<int:pk>/', views.UpdateSubGrantGoal.as_view(), name="update_sgg"),
    path('delete/subgrantgoal/<int:pk>/', views.DeleteSubGrantGoal.as_view(), name="delete_sgg"),
    ### GOAL URLS ###
    path('list/goal/', views.ListGoal.as_view(), name="list_ggg"),
    path('new/goal/', views.NewGoal.as_view(), name="create_ggg"),
    path('detail/goal/<int:pk>/', views.DetailGoal.as_view(), name="detail_ggg"),
    path('update/goal/<int:pk>/', views.UpdateGoal.as_view(), name="update_ggg"),
    path('delete/goal/<int:pk>/', views.DeleteGoal.as_view(), name="delete_ggg"),
    ### ISSUE URLS ###
    path('list/issue/', views.ListIssue.as_view(), name="list_is"),
    path('new/issue/', views.NewIssue.as_view(), name="create_is"),
    path('detail/issue/<int:pk>/', views.DetailIssue.as_view(), name="detail_is"),
    path('update/issue/<int:pk>/', views.UpdateIssue.as_view(), name="update_is"),
    path('delete/issue/<int:pk>/', views.DeleteIssue.as_view(), name="delete_is"),

]
    

pem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

core/forms.py
from django import forms

from core import models

class NewGrantGoalForm(forms.ModelForm):
    class Meta:
        model = models.GrantGoal
        fields = [
            "ggname",
            "user",
            "description",
            "days_duration",
            "state",
            "priority",
            "slug"
        ]
        widgets = {
            "ggname": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el grantgoal name!"}),
            "description": forms.Textarea(attrs={"type":"text", "class":"form-control", "row": 3, "placeholder":"Escribe el grantgoal description!"}),
            "user": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "days_duration": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "priority": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "state": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "slug": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el grantgoal slug!"}),
        }


class UpdateGrantGoalForm(forms.ModelForm):
    class Meta:
        model = models.GrantGoal
        fields = [
            "ggname",
            "user",
            "description",
            "days_duration",
            "state",
            "priority",
            "slug"
        ]
        widgets = {
            "ggname": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el grantgoal name!"}),
            "description": forms.Textarea(attrs={"type":"text", "class":"form-control", "row": 3, "placeholder":"Escribe el grantgoal description!"}),
            "user": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "days_duration": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "priority": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "state": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "slug": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el grantgoal slug!"}),
        }

### SUBGRANTGOALS FORMS ###

class NewSubGrantGoalForm(forms.ModelForm):
    class Meta:
        model = models.SubGrantGoal
        fields = [
            "sggname",
            "user",
            "area",
            "grantgoal",
            "description",
            "days_duration",
            "state",
            "priority",
            "slug"
        ]
        widgets = {
            "ggname": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el grantgoal name!"}),
            "description": forms.Textarea(attrs={"type":"text", "class":"form-control", "row": 3, "placeholder":"Escribe el grantgoal description!"}),
            "user": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "area": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "grantgoal": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "days_duration": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "priority": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "state": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "slug": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el grantgoal slug!"}),
        }
class UpdateSubGrantGoalForm(forms.ModelForm):
    class Meta:
        model = models.SubGrantGoal
        fields = [
            "sggname",
            "user",
            "area",
            "grantgoal",
            "description",
            "days_duration",
            "state",
            "priority",
            "slug"
        ]
        widgets = {
            "ggname": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el grantgoal name!"}),
            "description": forms.Textarea(attrs={"type":"text", "class":"form-control", "row": 3, "placeholder":"Escribe el grantgoal description!"}),
            "user": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "area": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "grantgoal": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "days_duration": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "priority": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "state": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "slug": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el grantgoal slug!"}),
        }


        #### GOALS FORMS ###
class NewGoalForm(forms.ModelForm):
    class Meta:
        model = models.Goal
        fields = [
            "goalname",
            "user",
            "area",
            "subgrantgoal",
            "description",
            "days_duration",
            "state",
            "priority",
            "slug"
        ]
        widgets = {
            "goalname": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el goal name!"}),
            "description": forms.Textarea(attrs={"type":"text", "class":"form-control", "row": 3, "placeholder":"Escribe el goal description!"}),
            "user": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "area": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "subgrantgoal": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "days_duration": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "priority": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "state": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "slug": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el goal slug!"}),
        }
class UpdateGoalForm(forms.ModelForm):
    class Meta:
        model = models.Goal
        fields = [
            "goalname",
            "user",
            "area",
            "subgrantgoal",
            "description",
            "days_duration",
            "state",
            "priority",
            "slug"
        ]
        widgets = {
            "goalname": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el grantgoal name!"}),
            "description": forms.Textarea(attrs={"type":"text", "class":"form-control", "row": 3, "placeholder":"Escribe el grantgoal description!"}),
            "user": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "area": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "subgrantgoal": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "days_duration": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "priority": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "state": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "slug": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el grantgoal slug!"}),
        }
### ISSUES FORMS ###
class NewIssueForm(forms.ModelForm):
    class Meta:
        model = models.Issue
        fields = [
            "issuename",
            "user",
            "area",
            "goal",
            "description",
            "days_duration",
            "state",
            "priority",
            "slug"
        ]
        widgets = {
            "issuename": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el goal name!"}),
            "description": forms.Textarea(attrs={"type":"text", "class":"form-control", "row": 3, "placeholder":"Escribe el goal description!"}),
            "user": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "area": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "goal": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "days_duration": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "priority": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "state": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "slug": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el goal slug!"}),
        }

class UpdateIssueForm(forms.ModelForm):
    class Meta:
        model = models.Issue
        fields = [
            "issuename",
            "user",
            "area",
            "goal",
            "description",
            "days_duration",
            "state",
            "priority",
            "slug"
        ]
        widgets = {
            "issuename": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el issue name!"}),
            "description": forms.Textarea(attrs={"type":"text", "class":"form-control", "row": 3, "placeholder":"Escribe el issue description!"}),
            "user": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "area": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "goal": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "days_duration": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "priority": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "state": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "slug": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el issue slug!"}),
        }

core/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

# Create your views here.

from core import models
from core import forms


# # # # #  C R U D G R A N T G O A L S # # # # #


# # # C R E A T E # # #
class NewGrantGoal(generic.CreateView):
    template_name = "core/create_gg.html"
    model = models.GrantGoal
    form_class = forms.NewGrantGoalForm
    success_url = reverse_lazy("core:list_gg")


# # # R E T R I E V E # # #
# # List
class ListGrantGoal(generic.View):
    template_name = "core/list_gg.html"
    context = {}

    def get(self, request):
        self.context = {
            "grantgoals": models.GrantGoal.objects.filter(status=True)
        }
        return render(request, self.template_name, self.context)

# # Detail
class DetailGrantGoal(generic.View):
    template_name = "core/detail_gg.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "grantgoal": models.GrantGoal.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)


# # # U P D A T E # # #
class UpdateGrantGoal(generic.UpdateView):
    template_name = "core/update_gg.html"
    model = models.GrantGoal
    form_class = forms.UpdateGrantGoalForm
    success_url = reverse_lazy("core:list_gg")


# # # D E L E T E # # #
class DeleteGrantGoal(generic.DeleteView):
    template_name = "core/delete_gg.html"
    model = models.GrantGoal
    success_url = reverse_lazy("core:list_gg")


# # # # #  -----------------C R U D S U B G R A N T G O A L S ------------------------# # # # #


# # # C R E A T E # # #
class NewSubGrantGoal(generic.CreateView):
    template_name = "core/create_sgg.html"
    model = models.SubGrantGoal
    form_class = forms.NewSubGrantGoalForm
    success_url = reverse_lazy("core:list_sgg")
# # # R E T R I E V E # # #
# # List
class ListSubGrantGoal(generic.ListView):
    template_name = "core/list_sgg.html"
    queryset = models.SubGrantGoal.objects.filter(status=True)


# # Detail

class DetailSubGrantGoal(generic.DetailView):
    template_name = "core/detail_sgg.html"
    model = models.SubGrantGoal

# # # U P D A T E # # #
class UpdateSubGrantGoal(generic.UpdateView):
    template_name = "core/update_sgg.html"
    model = models.SubGrantGoal
    form_class = forms.UpdateSubGrantGoalForm
    success_url = reverse_lazy("core:list_sgg")



# # # D E L E T E # # #

class DeleteSubGrantGoal(generic.DeleteView):
    template_name = "core/delete_sgg.html"
    model = models.SubGrantGoal
    success_url = reverse_lazy("core:list_sgg")




# # # # #  C R U D G O A L S # # # # #


# # # C R E A T E # # #
class NewGoal(generic.CreateView):
    template_name = "core/create_ggg.html"
    model = models.Goal
    form_class = forms.NewGoalForm
    success_url = reverse_lazy("core:list_ggg")

# # # R E T R I E V E # # #
# # List

class ListGoal(generic.ListView):
    template_name = "core/list_ggg.html"
    queryset = models.Goal.objects.filter(status=True)

# # Detail
class DetailGoal(generic.DetailView):
    template_name = "core/detail_ggg.html"
    model = models.Goal


# # # U P D A T E # # #
class UpdateGoal(generic.UpdateView):
    template_name = "core/update_ggg.html"
    model = models.Goal
    form_class = forms.UpdateGoalForm
    success_url = reverse_lazy("core:list_ggg")


# # # D E L E T E # # #

class DeleteGoal(generic.DeleteView):
    template_name = "core/delete_ggg.html"
    model = models.Goal
    success_url = reverse_lazy("core:list_ggg")

# # # # #  C R U D I S S U E S  # # # # #


# # # C R E A T E # # #
class NewIssue(generic.CreateView):
    template_name = "core/create_is.html"
    model = models.Issue
    form_class = forms.NewIssueForm
    success_url = reverse_lazy("core:list_is")

# # # R E T R I E V E # # #
# # List

class ListIssue(generic.ListView):
    template_name = "core/list_is.html"
    queryset = models.Issue.objects.filter(status=True)


# # Detail

class DetailIssue(generic.DetailView):
    template_name = "core/detail_is.html"
    model = models.Issue

# # # U P D A T E # # #

class UpdateIssue(generic.UpdateView):
    template_name = "core/update_is.html"
    model = models.Issue
    form_class = forms.UpdateIssueForm
    success_url = reverse_lazy("core:list_is")

# # # D E L E T E # # #

class DeleteIssue(generic.DeleteView):
    template_name = "core/delete_is.html"
    model = models.Issue
    success_url = reverse_lazy("core:list_is")

# # # # #  C R U D A R E A S # # # # #


# # # C R E A T E # # #


# # # R E T R I E V E # # #
# # List
# # Detail



# # # U P D A T E # # #



# # # D E L E T E # # #

templates/core/create_gg.html
{% extends "base/base.html" %}

{% block title %}NEW GRANT GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-outline-success form-control">New GrantGoal</button>
            <a href="{% url 'core:list_gg' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

templates/core/create_ggg.html
{% extends "base/base.html" %}

{% block title %}NEW GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-outline-success form-control">New Goal</button>
            <a href="{% url 'core:list_ggg' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

templates/core/create_is.html
{% extends "base/base.html" %}

{% block title %}NEW ISSUE VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-outline-success form-control">New Issue</button>
            <a href="{% url 'core:list_is' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

templates/core/create_sgg.html
{% extends "base/base.html" %}

{% block title %}NEW SUB GRANT GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-outline-success form-control">New Sub GrantGoal</button>
            <a href="{% url 'core:list_sgg' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

templates/core/delete_gg.html
{% extends "base/base.html" %}

{% block title %}DELETE GRANT GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            <h2>¿Realmente deseas eliminar este GrantGoal: <code>{{ object }}</code> ?</h2>
            
            <button type="submit" class="btn btn-outline-danger form-control">Delete GrantGoal</button>
            <a href="{% url 'core:list_gg' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

templates/core/delete_is.html
{% extends "base/base.html" %}

{% block title %}DELETE ISSUE VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            <h2>¿Realmente deseas eliminar esta ISSUE: <code>{{ object }}</code> ?</h2>
            
            <button type="submit" class="btn btn-outline-danger form-control">Delete Issue</button>
            <a href="{% url 'core:list_is' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

templates/core/delete_sgg.html
{% extends "base/base.html" %}

{% block title %}DELETE SUB GRANT GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            <h2>¿Realmente deseas eliminar este Sub GrantGoal: <code>{{ object }}</code> ?</h2>
            
            <button type="submit" class="btn btn-outline-danger form-control">Delete Sub GrantGoal</button>
            <a href="{% url 'core:list_sgg' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

templates/core/detail_ggg.html
{% extends "base/base.html" %}

{% block title %}DETAIL GOAL VIEW{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          General Data
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          The Goal name is: <strong>{{ object.goalname }}</strong> and Its Description is: {{ object.description }}
          <strong>Its progress: {{ object.progress }}</strong>
          the grantgoal relate is: <code>{{ object.user }}</code>.
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Date Data
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          The timestamp for the grantgoal is: <strong>{{ object.timestamp }}.</strong> Its final date is: {{ object.final_date }} and its days duration:  <code>{{ object.days_durations }}</code>.
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          STATUS DATA
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          The Status for the goal is: <strong>{{object.status }}</strong> Its state is: {{object.state }} and the priority is:  <code>{{ object.priority }}</code>.
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/core/list_ggg.html
{% extends "base/base.html" %}

{% block title %}GOAL LIST VIEW{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col">
            <a href="{% url 'core:create_ggg' %}" class="btn btn-outline-success form-control">New Goal</a>
        </div>
    </div>
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>NAME</th>
            <th>USER</th>
            <th>SUBGRANTGOAL</th>
            <th>DAYSDUR</th>
            <th>TIMESTAMP</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for gg in object_list %}
                <tr>
                    <td>{{ gg.id }}</td>
                    <td>{{ gg.goalname }} <br><progress id="file" value="{{ggg.progress}}" max="100"> 32% </progress></td>
                    <td>{{ gg.user }}</td>
                    <td>{{gg.subgrantgoal}} <br><progress id="file" value="{{sgg.progress}}" max="100"></progress> </td>
                    <td>{{ gg.days_duration }}</td>
                    <td>{{ gg.timestamp }}</td>
                    <td><a href="{% url 'core:detail_ggg' gg.pk %}" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="{% url 'core:update_ggg' gg.pk %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'core:delete_ggg' gg.pk %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

templates/core/list_is.html
{% extends "base/base.html" %}

{% block title %}ISSUE LIST VIEW{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col">
            <a href="{% url 'core:create_is' %}" class="btn btn-outline-success form-control">New Issue</a>
        </div>
    </div>
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>NAME</th>
            <th>USER</th>
            <th>GOAL</th>
            <th>DAYSDUR</th>
            <th>TIMESTAMP</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for gg in object_list %}
                <tr>
                    <td>{{ gg.id }}</td>
                    <td>{{ gg.issuename }} <br><progress id="file" value="{{gg.progress}}" max="100"> 32% </progress></td>
                    <td>{{ gg.user }}</td>
                    <td>{{gg.goal}} <br><progress id="file" value="{{gg.progress}}" max="100"></progress> </td>
                    <td>{{ gg.days_duration }}</td>
                    <td>{{ gg.timestamp }}</td>
                    <td><a href="{% url 'core:detail_is' gg.pk %}" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="{% url 'core:update_is' gg.pk %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'core:delete_is' gg.pk %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

templates/core/list_sgg.html
{% extends "base/base.html" %}

{% block title %}GRANTGOAL LIST VIEW{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col">
            <a href="{% url 'core:create_sgg' %}" class="btn btn-outline-success form-control">New Sub Grant Goal</a>
        </div>
    </div>
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>NAME</th>
            <th>USER</th>
            <th>GRANTGOAL</th>
            <th>DAYSDUR</th>
            <th>TIMESTAMP</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for gg in object_list %}
                <tr>
                    <td>{{ gg.id }}</td>
                    <td>{{ gg.sggname }} <br><progress id="file" value="{{sgg.progress}}" max="100"></progress> </td>
                    <td>{{ gg.user }}</td>
                    <td>{{gg.grantgoal}} <br><progress id="file" value="{{sgg.progress}}" max="100"></progress> </td>
                    <td>{{ gg.days_duration }}</td>
                    <td>{{ gg.timestamp }}</td>
                    <td><a href="{% url 'core:detail_sgg' gg.pk %}" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="{% url 'core:update_sgg' gg.pk %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'core:delete_sgg' gg.pk %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

templates/core/update_is.html
{% extends "base/base.html" %}

{% block title %}UPDATE ISSUE VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-outline-primary form-control">Update Issue</button>
            <a href="{% url 'core:list_is' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

templates/core/update_sgg.html
{% extends "base/base.html" %}

{% block title %}UPDATE SUB GRANT GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-outline-primary form-control">Update SUB GrantGoal</button>
            <a href="{% url 'core:list_sgg' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}